apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: springdemo-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/sexymanalive/argocd-gitops-itp.git
   targetRevision: HEAD
   path: ./springboot-chart
 destination:
   namespace: default
   server: https://kubernetes.default.svc
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - Validate=false
