# Blue deployment (Current version )

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-blue-app
  labels: 
    app: demo-app
    replicas: blue 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-app
      replicas: blue 
  template:
    metadata:
      labels:
        app: demo-app
        replicas: blue 
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine 
        ports:
        - containerPort: 80
