# green deployment (Current version )

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-green-app
  labels: 
    app: demo-app
    replicas: green 
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: demo-app
      replicas: green 
  template:
    metadata:
      labels:
        app: demo-app
        replicas: green 
    spec:
      containers:
      - name: demo-app
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
