apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-rs
  labels:
    app: my-nginx-app
spec:
  replicas: 4 # our desired number is 4 pods 
  selector:
    matchLabels:
      app: my-nginx-app 
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
        - name: nginx-container 
          image: nginx:alpine 
          ports: 
            - containerPort: 80 
