apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl 
spec:
  replicas: 4
  strategy: 
    # type: Recreate 
    type: RollingUpdate
    # rollingUpdate: 
      # maxSurge: 
      # maxUnavailable: 
  selector:
    matchLabels:
      app: nginx-app 
  template:
    metadata:
      labels:
        app: nginx-app 
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine #v1
        #image: 69966/earthdx:78 #v2
        ports:
        - containerPort: 80
