apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod

  # labels:
  #   app.kubernetes.io/name: myapp
spec:
  containers:
  - name: nginx-container 
    image: nginx:alpine 
    ports:
      - containerPort: 80
