apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeselector-dpl
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: nginx-nodeselector-app
  template:
    metadata:
      labels:
        app: nginx-nodeselector-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values: 
                      - nvme 
      containers:
      - name: nginx-nodeselector-app
        image: nginx:latest
        ports:
        - containerPort: 80
