# Blue deployment (Current version )

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-blue-app
  labels: 
    app: demo-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
    
  template:
    metadata:
      labels:
        app: demo-app
   
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine 
        ports:
        - containerPort: 80
