apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-fileupload-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: spring-fileupload-sc
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /srv/nfs_shared/spring-demo-pv
    server: 10.148.0.2

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-fileupload-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: spring-fileupload-sc
  accessModes:
    - ReadWriteMany
