apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-pvc-demo
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
